[package]
name = "fronius_meter_emulation"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
rumqttc = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44", features = ["full"] }
tokio-modbus = { version = "0.17", features = [
    "server",
    "tcp",
    "tcp-server",
] }
tracing-subscriber = "0.3"

[dev-dependencies]
mockito = "1.7.0"

[profile.release]
lto = true
strip = true
panic = "abort"
