services:
  fronius-meter-emulation:
    restart: always
    network_mode: host
    image: ghcr.io/soylentorange/fronius_meter_emulation:latest
    environment:
      # Modbus Server Settings
      # Set port to 502 or 1502 for Fronius Symo Gen24 (502 is problematic though, probably need to run as root)
      - FRONIUS_MODBUS_BIND=0.0.0.0:1502
      # set slave-id to 1 to 14 or 84 to 127 for Fronius Symo Gen24
      - FRONIUS_MODBUS_SLAVE_ID=126
      - INVERTER_SERIAL=123456789

      # MQTT Broker Settings
      - MQTT_BROKER_HOST=192.168.178.244
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=opendtu/# 
      - MQTT_USER=your_mqtt_username
      - MQTT_PASSWORD=your_mqtt_password

    healthcheck:
      test: netstat -an | grep 1502 > /dev/null; if [ 0 != $? ]; then exit 1; fi;
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
